#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/renan/Downloads/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/renan/Downloads/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/renan/LASCON2016/Projeto/code/pyneuron_v1.2/x86_64/.libs/libnrnmech.so" "$@"
